_prefs: 
  baselayer: ''
  print: true
  saveCenter: false
_properties: {}
attribution: "<a href='https://transcaucasiantrail.org' target='_blank'>&copy; TCTA &copy; OpenStreetMap</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 42.4113
  - 43.0812
  - 12
description: Style for hiking maps in the Caucasus
format: "png8:m=h"
interactivity_layer: ''
layers: 
  - landcover
  - dense_forest
  - mechseri
  - herbaceous
  - glaciers
  - landuse
  - contour.line
  - sov-lines
  - hillshade
  - waterway
  - water
  - aeroway
  - barrier_line
  - building
  - landuse_overlay
  - tunnel
  - road
  - bridge
  - admin
  - svaneti-racha-border
  - grid1330
  - mapping-tasks
  - osmtm_tasks_4
  - utm-lines
  - country_label_line
  - tracksmaster
  - just-tct
  - country_label
  - marine_label
  - state_label
  - place_label
  - water_label
  - peaks
  - mountain_pass
  - mountain_peak_label
  - poi_label
  - road_label
  - waterway_label
  - housenum_label
  - contour.label
maxzoom: 20
minzoom: 0
name: hikeOSM
source: "mapbox:///mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v7,tct.9c2d453a,tct.dabiwpod,tct.bayra4t9,tct.5cbwyx2h,tct.7xtuqxiy,tct.7pscrkhh,tct.0acy2lm6,tct.br86tmat,tct.81e5wlz3,tct.6itt4u7y,tct.5nlnyzd0,tct.59210768,tct.67807749"
styles: 
  - style.mss
  - road.mss
  - label.mss
  - poi.mss
  - grid.mss
template: ''
